# Copyright (C) 2018 Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Wazuh master Service: API and registration (authd)

apiVersion: v1
kind: Service
metadata:
#  name: wazuh
  name: {{ template "app.name" . }}-master  # Don't change, unless you update the Wazuh Kibana app config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "app.name" . }}-manager
    # dns: route53
{{- if (index .Values "master-svc" "annotations") }}    
  annotations:
{{ toYaml (index .Values "master-svc" "annotations") | indent 4 }}
{{- end }}    
spec:
  type: {{ (index .Values "master-svc" "type") }}
  selector:
    app: {{ template "app.name" . }}-manager
    node-type: master
  {{- with (index .Values "master-svc" "ports") }}
  ports:
  {{- .|toYaml|nindent 4}}
  {{- end }}
