version: &version 3.13.2_7.9.1

volume-mount-hack: &volume-mount-hack
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi

wazuh-elasticsearch:
  volume-mount-hack: *volume-mount-hack
  image: &wazuh-elasticsearch-image wazuh/wazuh-elasticsearch
  es-rest-port: &es-rest-port 9200
  es-nodes-port: &es-nodes-port 9300
  ports: &wazuh-elasticsearch-ports
    - containerPort: *es-rest-port
      name: es-rest
    - containerPort: *es-nodes-port
      name: es-nodes
  cluster:
    enabled: false
    elasticsearchPersistentVolumeCluster: &elasticsearchPersistentVolumeCluster
      wazuh-elasticsearch-elasticsearch:
        mountPath: /usr/share/elasticsearch/data
        reclaimPolicy: Retain
        capacity: 10Gi
        storageClassName: microk8s-hostpath
        accessModes:
          - ReadWriteOnce
    data-sts:
      image: wazuh/wazuh-elasticsearch
      version: *version
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 1
          memory: 2Gi
      ports: *wazuh-elasticsearch-ports
      persistentVolume: *elasticsearchPersistentVolumeCluster        
    master-sts:
      image: wazuh/wazuh-elasticsearch
      version: *version
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 1
          memory: 2Gi
      ports: *wazuh-elasticsearch-ports
      persistentVolume: *elasticsearchPersistentVolumeCluster
    api-svc:
      ports:
      - name: es-rest
        port: *es-rest-port
        targetPort: *es-rest-port
  single-node:
    elasticsearchPersistentVolumeSingleNode: &elasticsearchPersistentVolumeSingleNode
      wazuh-elasticsearch-elasticsearch:
        mountPath: /usr/share/elasticsearch/data
        reclaimPolicy: Retain
        capacity: 30Gi
        storageClassName: microk8s-hostpath
        accessModes:
          - ReadWriteOnce
    enabled: true
    sts:
      image: wazuh/wazuh-elasticsearch
      version: *version
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 1
          memory: 2Gi
      ports: *wazuh-elasticsearch-ports   
      persistentVolume: *elasticsearchPersistentVolumeSingleNode
wazuh-managers:
  volume-mount-hack: *volume-mount-hack
  master-sts:
    image: wazuh/wazuh
    version: *version
    resources:
      requests:
        cpu: 2
        memory: 1024Mi
      limits:
        cpu: 2
        memory: 2048Mi
    ports:
      - containerPort: 1515
        name: registration
      - containerPort: 1516
        name: cluster
      - containerPort: 55000
        name: api
    persistentVolume:     
      wazuh-managers-manager-master:
          mountPath: /var/ossec/data
          reclaimPolicy: Retain
          capacity: 50Gi
          storageClassName: microk8s-hostpath
          accessModes:
            - ReadWriteOnce  
  worker-sts:
    image: wazuh/wazuh
    version: *version
    resources:
      requests:
        cpu: 2
        memory: 1024Mi
      limits:
        cpu: 2
        memory: 2048Mi
    ports:
      - containerPort: 1514
        name: agents-events
      - containerPort: 1516
        name: cluster 
    persistentVolume:     
      wazuh-managers-manager-worker:
          mountPath: /var/ossec/data
          reclaimPolicy: Retain
          capacity: 10Gi
          storageClassName: microk8s-hostpath
          accessModes:
            - ReadWriteOnce      
wazuh-kibana:
  volume-mount-hack: *volume-mount-hack
  image: wazuh/wazuh-kibana
  version: *version
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 400m
      memory: 2048Mi
  ports:
    - containerPort: 5601
      name: kibana    
  nginx:
    image: wazuh/wazuh-nginx
    version: *version
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
    ports:
      - containerPort: 80
      - containerPort: 443    
  