wazuh-elasticsearch:
  image: &wazuh-elasticsearch-image wazuh/wazuh-elasticsearch:3.13.2_7.9.1
  cluster:
    enabled: true
    data-sts:
      image: *wazuh-elasticsearch-image
    master-sts:
      image: *wazuh-elasticsearch-image
  single-node:
    enabled: true
    sts:
      image: *wazuh-elasticsearch-image
wazuh-managers:
  master-sts:
    image: wazuh/wazuh:3.13.2_7.9.1
wazuh-kibana:
  image: wazuh/wazuh-kibana:3.13.2_7.9.1
  nginx:
    image: wazuh/wazuh-nginx:3.13.2_7.9.1
  