version: &version 3.13.2_7.9.1

volume-mount-hack: &volume-mount-hack
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi

api-port: &api-port 55000
es-rest-port: &es-rest-port 9200
es-nodes-port: &es-nodes-port 9300
registration-port: &registration-port 1515
cluster-port: &cluster-port 1516
agents-events-port: &agents-events-port 1514
web-https-port: &web-https-port 443
kibana-port: &kibana-port 5601
  
wazuh-elasticsearch:
  volume-mount-hack: *volume-mount-hack
  image: &wazuh-elasticsearch-image wazuh/wazuh-elasticsearch
  es-rest-port: *es-rest-port
  es-nodes-port: *es-nodes-port
  ports: &wazuh-elasticsearch-ports
    - containerPort: *es-rest-port
      name: es-rest
    - containerPort: *es-nodes-port
      name: es-nodes
  cluster:
    enabled: false
    elasticsearchPersistentVolumeCluster: &elasticsearchPersistentVolumeCluster
      wazuh-elasticsearch-elasticsearch:
        mountPath: /usr/share/elasticsearch/data
        reclaimPolicy: Retain
        capacity: 10Gi
        storageClassName: microk8s-hostpath
        accessModes:
          - ReadWriteOnce
    data-sts:
      image: wazuh/wazuh-elasticsearch
      version: *version
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 1
          memory: 2Gi
      ports: *wazuh-elasticsearch-ports
      persistentVolume: *elasticsearchPersistentVolumeCluster        
    master-sts:
      image: wazuh/wazuh-elasticsearch
      version: *version
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 1
          memory: 2Gi
      ports: *wazuh-elasticsearch-ports
      persistentVolume: *elasticsearchPersistentVolumeCluster
    api-svc:
      ports:
      - name: es-rest
        port: *es-rest-port
        targetPort: *es-rest-port
    svc: 
      ports:
      - name: es-nodes
        port: *es-nodes-port
        targetPort: *es-nodes-port
  single-node:
    elasticsearchPersistentVolumeSingleNode: &elasticsearchPersistentVolumeSingleNode
      wazuh-elasticsearch-elasticsearch:
        mountPath: /usr/share/elasticsearch/data
        reclaimPolicy: Retain
        capacity: 30Gi
        storageClassName: microk8s-hostpath
        accessModes:
          - ReadWriteOnce
    enabled: true
    sts:
      image: wazuh/wazuh-elasticsearch
      version: *version
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 1
          memory: 2Gi
      ports: *wazuh-elasticsearch-ports   
      persistentVolume: *elasticsearchPersistentVolumeSingleNode
    api-svc:
      ports:
      - name: es-rest
        port: *es-rest-port
        targetPort: *es-rest-port  
wazuh-managers: 
  volume-mount-hack: *volume-mount-hack  
  registration-port: *registration-port
  cluster-port: *cluster-port
  api-port: *api-port
  agents-events-port: *agents-events-port
  master-sts:
    image: wazuh/wazuh
    version: *version
    resources:
      requests:
        cpu: 2
        memory: 1024Mi
      limits:
        cpu: 2
        memory: 2048Mi
    ports:
      - containerPort: *registration-port
        name: registration
      - containerPort: *cluster-port
        name: cluster
      - containerPort: *api-port
        name: api    
    persistentVolume:     
      wazuh-managers-manager-master:
          mountPath: /var/ossec/data
          reclaimPolicy: Retain
          capacity: 50Gi
          storageClassName: microk8s-hostpath
          accessModes:
            - ReadWriteOnce 
  worker-sts:
    image: wazuh/wazuh
    version: *version
    resources:
      requests:
        cpu: 2
        memory: 1024Mi
      limits:
        cpu: 2
        memory: 2048Mi
    ports:
      - containerPort: *agents-events-port
        name: agents-events
      - containerPort: *cluster-port
        name: cluster 
    persistentVolume:     
      wazuh-managers-manager-worker:
          mountPath: /var/ossec/data
          reclaimPolicy: Retain
          capacity: 10Gi
          storageClassName: microk8s-hostpath
          accessModes:
            - ReadWriteOnce
  master-svc:
    ports:
    - name: registration
      port: *registration-port
      targetPort: *registration-port
    - name: api
      port: *api-port
      targetPort: *api-port
  cluster-svc:
    ports:
    - name: cluster
      port: *cluster-port
      targetPort: *cluster-port       
  workers-svc:
    ports:
    - name: agents-events
      port: *agents-events-port
      targetPort: *agents-events-port   
wazuh-kibana:
  volume-mount-hack: *volume-mount-hack
  web-https-port: *web-https-port
  kibana-port: *kibana-port 
  image: wazuh/wazuh-kibana
  api-port: *api-port
  version: *version
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 400m
      memory: 2048Mi
  ports:
    - containerPort: *kibana-port
      name: kibana
  svc:
    ports:
    - name: kibana
      port: *kibana-port
      targetPort: *kibana-port
  nginx:
    image: wazuh/wazuh-nginx
    version: *version
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
    ports:
      - containerPort: 80
      - containerPort: *web-https-port 
  nginx-svc:
    ports:
    - name: web-https
      port: *web-https-port
      targetPort: *web-https-port    
  