# Copyright (C) 2018 Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Elasticsearch StatefulSet: 3 master nodes.

{{- if .Values.cluster.enabled }}

{{- $this := . }}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "app.name" . }}-elasticsearch
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "app.name" . }}-elasticsearch
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ template "app.name" . }}-elasticsearch
  serviceName: {{ template "app.name" . }}-elasticsearch
  template:
    metadata:
      labels:
        app: {{ template "app.name" . }}-elasticsearch
      name: {{ template "app.name" . }}-elasticsearch
    spec:
      # Set the wazuh-elasticsearch volume permissions so the elasticsearch user can use it!
      initContainers:
{{- if .Values.persistentVolume }}        
        - name: volume-mount-hack
          image: busybox
          {{- with (index .Values "volume-mount-hack" "resources") }}
          resources:
          {{- .|toYaml|nindent 12}}
          {{- end }}
          command:
            - sh
            - '-c'
            {{- range $vmName, $vmData := .Values.persistentVolume }}
            - 'chown -R 1000:1000 {{ $vmData.mountPath }}'
            {{- end }}
          volumeMounts:
            {{- range $vmName, $vmData := .Values.persistentVolume }}
            - mountPath: {{ $vmData.mountPath }}
              name: {{ $vmName }}
            {{- end }} 
{{- end }}
        - name: increase-the-vm-max-map-count
          image: busybox
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          securityContext:
            privileged: true
      containers:
        - name: {{ template "app.name" . }}-elasticsearch
          image: "{{ index .Values.cluster "master-sts" "image" }}:{{ index .Values.cluster "master-sts" "version" }}"
          {{- with (index .Values.cluster "master-sts" "resources") }}
          resources:
          {{- .|toYaml|nindent 12}}
          {{- end }}
          env:
            - name: ES_JAVA_OPTS
              value: '-Xms512m -Xmx512m'
            - name: node.master
              value: 'true'
            - name: node.data
              value: 'false'
            - name: node.ingest
              value: 'false'
            - name: bootstrap.memory_lock
              value: 'false'
            - name: cluster.name
              value: wazuh
            - name: network.host
              value: 0.0.0.0
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: discovery.zen.ping.unicast.hosts
              value: {{ template "app.name" . }}-elasticsearch
            - name: discovery.zen.minimum_master_nodes
              value: "2"
            - name: ELASTICSEARCH_URL
              value: "{{ template "app.name" . }}-elasticsearch:{{ index .Values "es-rest-port" }}"  
          {{- with (index .Values.cluster "master-sts" "ports") }}    
          ports:
          {{- .|toYaml|nindent 12}}
          {{- end }}   
{{- if .Values.persistentVolume }}
          volumeMounts:
            {{- range $vmName, $vmData := .Values.persistentVolume }}
            - mountPath: {{ $vmData.mountPath }}
              name: {{ $vmName }}
            {{- end }} 
      volumes:
        {{- range $vmName, $vmData := .Values.persistentVolume }}
        {{- if $vmData.existingClaim }}
        - name: {{ $vmName }}
          persistentVolumeClaim:
            claimName: {{ $vmData.existingClaim }}
        {{- end }}
        {{- end }} 
  volumeClaimTemplates:
    {{- range $vmName, $vmData := .Values.persistentVolume }}
      {{- if (not $vmData.existingClaim) }}
    - metadata:
        name: {{ $vmName }}
        namespace: {{ .Release.Namespace }}
      spec:
          {{- if (not $vmData.storageClassName) }}
        selector:
          matchLabels:
            app: {{ template "app.name" $this }}-elasticsearch
            release: {{ $this.Release.Name }}
          {{- end }}
        resources:
          requests:
            storage: {{ $vmData.capacity }}
          {{- if $vmData.storageClassName }}
        storageClassName: {{ $vmData.storageClassName }}
          {{- end }}
          {{- if $vmData.accessModes }}
        accessModes:
          {{- range $item := $vmData.accessModes }}
          - {{ $item }}
          {{- end }}
          {{- end }}
      {{- end }}
    {{- end }}
{{- end }}
{{- end }}