# Copyright (C) 2018 Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Wazuh master Service: API and registration (authd)

apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.name" . }}  # Don't change, unless you update the Wazuh Kibana app config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "app.name" . }}-manager
    # dns: route53
  annotations:
    # domainName: 'changeme'
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
spec:
  type: LoadBalancer
  selector:
    app: {{ template "app.name" . }}-manager
    node-type: master
  {{- with (index .Values "master-svc" "ports") }}
  ports:
  {{- .|toYaml|nindent 4}}
  {{- end }}
