# Copyright (C) 2018 Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Wazuh master StatefulSet

{{- $this := . }}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "app.name" . }}-manager-master
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "app.name" . }}-manager-master
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "app.name" . }}-manager
      node-type: master
  serviceName: {{ template "app.name" . }}-cluster
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: {{ template "app.name" . }}-manager
        node-type: master
      name: {{ template "app.name" . }}-manager-master
    spec:
      containers:
        - name: {{ template "app.name" . }}-manager
          image: "{{ index .Values "master-sts" "image" }}:{{ index .Values "master-sts" "version" }}"
          {{- with (index .Values "master-sts" "resources") }}
          resources:
          {{- .|toYaml|nindent 12}}
          {{- end }}
          {{- with (index .Values "master-sts" "ports") }}
          ports:
          {{- .|toYaml|nindent 12}}
          {{- end }} 
          env:
          {{- range $key, $value := (index .Values "master-sts" "env")}}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
{{- if (index .Values "master-sts" "persistentVolume") }} 
          volumeMounts:
            {{- range $vmName, $vmData := (index .Values "master-sts" "persistentVolume") }}
            - mountPath: {{ $vmData.mountPath }}
              name: {{ $vmName }}
            {{- end }}
            - name: config
              mountPath: /wazuh-config-mount/etc/ossec.conf
              subPath: ossec.conf
              readOnly: true  
            - name: {{ template "app.name" . }}-authd-pass
              mountPath: /wazuh-config-mount/etc/authd.pass
              subPath: authd.pass
              readOnly: true
      volumes:
        {{- range $vmName, $vmData := (index .Values "master-sts" "persistentVolume") }}
        {{- if $vmData.existingClaim }}
        - name: {{ $vmName }}
          persistentVolumeClaim:
            claimName: {{ $vmData.existingClaim }}
        {{- end }}
        {{- end }} 
        - name: config
          configMap:
            name: {{ template "app.name" . }}-manager-master-conf
        - name: {{ template "app.name" . }}-authd-pass
          secret:
            secretName: {{ template "app.name" . }}-authd-pass      
  volumeClaimTemplates:
    {{- range $vmName, $vmData := (index .Values "master-sts" "persistentVolume") }}
      {{- if (not $vmData.existingClaim) }}
    - metadata:
        name: {{ $vmName }}
        namespace: {{ $this.Release.Namespace }}
      spec:
          {{- if (not $vmData.storageClassName) }}
        selector:
          matchLabels:
            app: {{ template "app.name" $this }}-manager-master
            release: {{ $this.Release.Name }}
          {{- end }}
        resources:
          requests:
            storage: {{ $vmData.capacity }}
          {{- if $vmData.storageClassName }}
        storageClassName: {{ $vmData.storageClassName }}
          {{- end }}
          {{- if $vmData.accessModes }}
        accessModes:
          {{- range $item := $vmData.accessModes }}
          - {{ $item }}
          {{- end }}
          {{- end }}
      {{- end }}
    {{- end }}
{{- end }}