# Copyright (C) 2018 Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Wazuh master StatefulSet

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "app.name" . }}-manager-master
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "app.name" . }}-manager
      node-type: master
  serviceName: {{ template "app.name" . }}-cluster
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: {{ template "app.name" . }}-manager
        node-type: master
      name: {{ template "app.name" . }}-manager-master
    spec:
      volumes:
        - name: config
          configMap:
            name: {{ template "app.name" . }}-manager-master-conf
        - name: {{ template "app.name" . }}-authd-pass
          secret:
            secretName: {{ template "app.name" . }}-authd-pass
      containers:
        - name: {{ template "app.name" . }}-manager
          image: 'wazuh/wazuh:3.13.2_7.9.1'
          resources:
            requests:
              cpu: 2
              memory: 1024Mi
            limits:
              cpu: 2
              memory: 2048Mi
          volumeMounts:
            - name: config
              mountPath: /wazuh-config-mount/etc/ossec.conf
              subPath: ossec.conf
              readOnly: true
            - name: {{ template "app.name" . }}-manager-master
              mountPath: /var/ossec/data
            - name: {{ template "app.name" . }}-authd-pass
              mountPath: /wazuh-config-mount/etc/authd.pass
              subPath: authd.pass
              readOnly: true
          ports:
            - containerPort: 1515
              name: registration
            - containerPort: 1516
              name: cluster
            - containerPort: 55000
              name: api
          env:
            - name: API_USER
              valueFrom:
                secretKeyRef:
                  name: {{ template "app.name" . }}-api-cred
                  key: username
            - name: API_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ template "app.name" . }}-api-cred
                  key: password
            - name: WAZUH_CLUSTER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "app.name" . }}-cluster-key
                  key: key
  volumeClaimTemplates:
    - metadata:
        name: {{ template "app.name" . }}-manager-master
        namespace: {{ .Release.Namespace }}
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: microk8s-hostpath
        resources:
          requests:
            storage: 50Gi
